### PR TITLE
Rename BackEndGrpc class to RemoteBackEnd

### PR DESCRIPTION
**Pull request by mechanism-s**
#276 Renamed `BackEndGrpc` class to `RemoteBackEnd`

### CODE REVIEW

**Comment by canepat** [comment]
> #276 Renamed `BackEndGrpc` class to `RemoteBackEnd`

Thanks for contributing!

**Review by canepat — APPROVED** [review]

**Comment by mechanism-s** [comment]
Thanks for the review! Is there anything I should do to trigger the circleci checks? I'm not sure they've actually run.

**Comment by canepat** [comment]
> Thanks for the review! Is there anything I should do to trigger the circleci checks? I'm not sure they've actually run.

It's just because CI was disabled for forked PRs. Please try now by changing `// SILKRPC_ETHBACKEND_BACKEND_GRPC_HPP_` comment at the end of `remote_backend.hpp`, that still uses the old naming.

**Comment by canepat** [comment]
> > Thanks for the review! Is there anything I should do to trigger the circleci checks? I'm not sure they've actually run.
> 
> It's just because CI was disabled for forked PRs. Please try now by changing `// SILKRPC_ETHBACKEND_BACKEND_GRPC_HPP_` comment at the end of `remote_backend.hpp`, that still uses the old naming.

I've just done the tiny change in comment to avoid linter error.

**Comment by mechanism-s** [comment]
Thanks for catching that, and for merging.

**Pull request merged**
